apiVersion: v1
kind: ConfigMap
metadata:
  name: fe-config
  namespace: practice
data:
  application.properties: |
    kafka.servers=kafka.practice.svc.cluster.local:9092
    beUrl=http://zoda-be-service:8081/kafka/findAll